### ISSUE TITLE
Failure to scan all Twitter and Facebook pages with Tracking Protection

### ISSUE THREAD

**Issue by AJCxZ0** [sneakypete81/updatescanner#218] opened 2018-03-02 19:57 UTC
Firefox version: 58.0.2
Update Scanner version: 4.2.0

Fresh Firefox profile with only `HTTPS Everywhere`, `Privacy Badger` and `Update Scanner` extensions and no pages on the scan list. Manually added pages to scan after encountering doc bug described in [Issue 199](https://github.com/sneakypete81/updatescanner/issues/199) including multiple Twitter and Facebook Posts pages, e.g. https://twitter.com/StevenWilsonHQ and https://www.facebook.com/pg/StevenWilsonHQ/posts/

After scanning all pages, all Twitter and Facebook Posts pages are greyed in the sidebar and opening any of them has an Update Scanner header with error, 
```This page has returned and error when scanned. Click the title above to see what's wrong```

![update scanner error - twitter](https://user-images.githubusercontent.com/14222236/36918963-9f871d26-1e29-11e8-92e5-df6b88df2e76.png)

Clicking the title loads the page, which has no errors.

Before I started this Firefox profile and manually added the pages to scan, starting with Firefox 57 and the new webextension, all these same pages scanned and rendered without error.

**Comment by AJCxZ0** [comment] 2018-03-22 04:16
Tested with a new profile and no other extensions installed. No problem scanning Twitter or Facebook pages.

1. Enabling extension _Privacy Badger_ and scanning all pages reproduces the reported problem. i.e.all Twitter and Facebook pages are greyed out.
1. Disabling extension _Privacy Badger_, enabling extension _HTTPS Everywhere_ and scanning all pages again leaves the Twitter and Facebook pages greyed out.
1. Disabling extension _HTTPS Everywhere_, leaving only _Update Scanner_ and scanning all pages again still leaves the Twitter and Facebook pages greyed out.
1. Removing extensions _Privacy Badger_ and _HTTPS Everywhere_, quitting and starting Firefox still leaves the Twitter and Facebook pages greyed out. There is a potential that the breakage was not introduced by the extensions, as they were installed by synchronising an existing Firefox profile. Further testing is needed.

**Comment by AJCxZ0** [comment] 2018-03-22 20:28
The problem is neither the _Privacy Badger_ nor _HTTPS Everywhere_ extension, but something sync'ed from my Firefox profile (with which _Update Scanner_ was working up until the situation reported).

**Comment by AJCxZ0** [comment] 2018-03-22 22:55
Further testing shows that while the Twitter and Facebook pages load fine in the browser, setting

    Tracking Protection
      Tracking Protection blocks online trackers that collect your browsing data across multiple websites.
      Learn more about Tracking Protection and your privacy
        Use Tracking Protection to block known trackers
          [x] Always
           
in `about:preferences#privacy` causes them all to error when scanned.

Title updated to reflect the specific problem.

**Comment by sneakypete81** [comment] 2018-04-04 08:02
Thanks for tracking this down. It looks like this is a common problem, and that it's expected Firefox behaviour to block requests like this from extensions when tracking protection is turned on (https://bugzilla.mozilla.org/show_bug.cgi?id=1308640).

https://github.com/cadeyrn/bookmarks-organizer/issues/26 is an example reported with another extension, along with a potential workaround (automatically suspend tracking protection while scanning).

**Comment by sneakypete81** [comment] 2018-04-04 19:28
https://bugzilla.mozilla.org/show_bug.cgi?id=1404610 explains why Firefox blocks extension access to certain websites when tracking protection is turned on.

**Comment by sneakypete81** [comment] 2018-04-14 20:00
Raised this as https://bugzilla.mozilla.org/show_bug.cgi?id=1454193

**Comment by sneakypete81** [comment] 2018-04-29 19:47
There's no way to fix this generally, but manually adding Twitter & Facebook to the permissions list seems to fix this problem.

Please try the 4.3.1beta1 release. See #36 for how to install Update Scanner beta versions.

**Comment by AJCxZ0** [comment] 2018-05-04 22:09
I watched and appreciate your efforts with upstream. Feel free to close or leave this ticket open as you see fit.

**Comment by manankov** [comment] 2018-07-20 09:48
How do I manually add Twitter and Facebook to my permission list?

**Comment by manankov** [comment] 2018-07-23 03:33
no, that doesn't help.

**Comment by sneakypete81** [comment] 2018-07-24 19:24
@manankov, could you please try this in a clean profile with no other extensions installed?

If you still see a problem that isn't covered by this issue, please raise a new issue with a detailed explanation of what went wrong and the exact steps to reproduce it.

**Comment by sneakypete81** [comment] 2018-10-20 13:58
Fixed in v4.3.1

**Closed by sneakypete81** 2018-10-20 13:58 UTC
Labels: bug
