### ISSUE TITLE
Does not work with site Bundle Stars

### ISSUE THREAD

**Issue by molitar** [sneakypete81/updatescanner#76] opened 2016-10-02 16:49 UTC
I find it will not work for sites like bundlestars at all.

https://www.bundlestars.com/

**Comment by sneakypete81** [comment] 2016-10-16 08:22
[Duplicate of #69]
Unfortunately that website uses Javascript to load its content. Update Scanner can only scan plain HTML web pages.

You can verify this by installing the Just Disable Stuff addon and selecting "Just Disable Javascript" from the Tools menu. When you go to https://www.bundlestars.com/ you'll see that the page doesn't load.

**Closed by sneakypete81** 2016-10-16 08:22 UTC
Labels: duplicate
