### ISSUE TITLE
"Scan all pages" broken

### ISSUE THREAD

**Issue by nji9nji9** [sneakypete81/updatescanner#547] opened 2019-10-25 15:29 UTC
v.4.4.0, FF 68.2.0esr (64bit), Win7
Symbol / Menu / "Scan all pages" gives no response.
Symbol / Sidebar / Click on one of the watched pages
gives "XYZ..." wants to save ... at ..." Yes/No?
From then on, it works.
Until some times later, when it is broken again,
and the same procedure as above.
Probably not only "Scan all pages" but at all?

**Comment by sneakypete81** [comment] 2019-10-26 05:55
Some of the Firefox privacy settings stop Update Scanner from working, see #235.

Can you reproduce this with a new Firefox profile? See https://github.com/sneakypete81/updatescanner/wiki#what-should-i-do-if-i-find-a-bug.

**Comment by nji9nji9** [comment] 2019-10-26 08:18
As mentioned above I use FF68.2.0esr.
https://bugzilla.mozilla.org/show_bug.cgi?id=1454192
says that a bug has been fixed in FF69.
Is that the only cause?

Or can you explicitly name the settings that have to made in FF
to make UpdateScanner work (if any?).
(Among others I use "clear cookies and website data on closing"
"strong" blocking of page elements ...)

**Comment by sneakypete81** [comment] 2019-10-28 22:08
Various privacy-related settings might prevent Update Scanner from working. I suggest starting with a new profile and enabling them one-by-one to see what the problem is.

**Comment by sneakypete81** [comment] 2019-11-30 20:26
Closing for now, but please update this if you have further information.

**Closed by sneakypete81** 2019-11-30 20:26 UTC
Labels: more info needed
