### ISSUE TITLE
Cannot scan and open pages anymore

### ISSUE THREAD

**Issue by Catuai** [sneakypete81/updatescanner#245] opened 2018-05-13 11:52 UTC
Windows 10
Update Scanner 4.3.0
Firefox 60.0 64 bit

Since a couple of days Update Scanner is not working. I have my list of websites, but I cannot scan them anymore. Also when I click on a website in the sidebar, I only get a white screen, the website is not opening.

I already deinstalled Update Scanner from Firefox and installed it again, but it does not help.

I would be happy to find a solution.

Thank you!

**Comment by tmo-github** [comment] 2018-06-07 12:06
MacOs Sierra 10.12.6
Update Scanner 4.3.0
Firefox 60.0.2 64 bit

Same issue here for a few weeks now.

**Comment by tmo-github** [comment] 2018-06-07 12:16
The problem is apparently identical to the one already discussed in two other issues: #232 and #239. I suggest to close this issue to avoid multiple entry points to following up on the problem.

**Comment by sneakypete81** [comment] 2018-06-15 07:59
Ok, thanks. This is waiting for a fix from Firefox, unfortunately - see #234.

**Closed by sneakypete81** 2018-06-15 07:59 UTC
